CREATE TYPE "public"."connection_health" AS ENUM('healthy', 'needs-attention', 'expired');--> statement-breakpoint
CREATE TYPE "public"."connection_kind" AS ENUM('scm', 'channel', 'tasks');--> statement-breakpoint
CREATE TABLE "connections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"provider" text NOT NULL,
	"kind" "connection_kind" NOT NULL,
	"label" text NOT NULL,
	"health" "connection_health" DEFAULT 'healthy' NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "connections" ADD CONSTRAINT "connections_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;