CREATE TABLE "repo_maps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repo_maps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"repo_full_name" text NOT NULL,
	"commit_sha" text NOT NULL,
	"content" text NOT NULL,
	"generation_cost_usd" double precision DEFAULT 0 NOT NULL,
	"generation_tokens" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "repo_maps_content_max_length" CHECK (char_length("repo_maps"."content") <= 16384)
);
--> statement-breakpoint
ALTER TABLE "repo_maps" ADD CONSTRAINT "repo_maps_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "repo_maps_org_repo_sha" ON "repo_maps" USING btree ("org_id","repo_full_name","commit_sha");