CREATE TABLE "run_context_retrievals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "run_context_retrievals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"item_id" integer,
	"item_title" text NOT NULL,
	"chunk_idx" integer NOT NULL,
	"rank" integer NOT NULL,
	"score" double precision NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "run_context_retrievals" ADD CONSTRAINT "run_context_retrievals_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "run_context_retrievals" ADD CONSTRAINT "run_context_retrievals_item_id_team_context_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."team_context_items"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "run_context_retrievals_run_id_idx" ON "run_context_retrievals" USING btree ("run_id");