CREATE TABLE "task_context_chunks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_context_chunks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"chunk_idx" integer NOT NULL,
	"text" text NOT NULL,
	"embedding" vector(384) NOT NULL,
	"embedding_model" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_context_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_context_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_id" integer NOT NULL,
	"org_id" integer NOT NULL,
	"title" text NOT NULL,
	"size_bytes" integer DEFAULT 0 NOT NULL,
	"sha256" text NOT NULL,
	"mime" text NOT NULL,
	"source" text DEFAULT 'upload' NOT NULL,
	"status" "context_item_status" DEFAULT 'pending' NOT NULL,
	"error" text,
	"indexed_at" timestamp with time zone,
	"uploaded_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "task_context_chunks" ADD CONSTRAINT "task_context_chunks_item_id_task_context_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."task_context_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_context_chunks" ADD CONSTRAINT "task_context_chunks_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_context_items" ADD CONSTRAINT "task_context_items_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_context_items" ADD CONSTRAINT "task_context_items_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_context_items" ADD CONSTRAINT "task_context_items_uploaded_by_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_context_items" ADD CONSTRAINT "task_context_items_org_id_sha256_content_blobs_org_id_sha256_fk" FOREIGN KEY ("org_id","sha256") REFERENCES "public"."content_blobs"("org_id","sha256") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "task_context_chunks_embedding_idx" ON "task_context_chunks" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "task_context_chunks_task_id_idx" ON "task_context_chunks" USING btree ("task_id");--> statement-breakpoint
CREATE UNIQUE INDEX "task_context_items_task_sha" ON "task_context_items" USING btree ("task_id","sha256");