CREATE TYPE "public"."connection_auth_kind" AS ENUM('none', 'api_token', 'oauth2');--> statement-breakpoint
CREATE TABLE "connection_secrets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connection_secrets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"ciphertext" text NOT NULL,
	"key_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "connections" ADD COLUMN "auth" "connection_auth_kind" DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "connections" ADD COLUMN "credential_ref" integer;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "external_ref" jsonb;--> statement-breakpoint
ALTER TABLE "connection_secrets" ADD CONSTRAINT "connection_secrets_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connections" ADD CONSTRAINT "connections_credential_ref_connection_secrets_id_fk" FOREIGN KEY ("credential_ref") REFERENCES "public"."connection_secrets"("id") ON DELETE set null ON UPDATE no action;