CREATE TABLE "codebase_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "codebase_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"repo_full_name" text NOT NULL,
	"setup_command" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "codebase_settings_setup_command_max_length" CHECK (char_length("codebase_settings"."setup_command") <= 4096)
);
--> statement-breakpoint
ALTER TABLE "codebase_settings" ADD CONSTRAINT "codebase_settings_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "codebase_settings_org_repo" ON "codebase_settings" USING btree ("org_id","repo_full_name");