CREATE TYPE "public"."memory_write_kind" AS ENUM('insert', 'reinforce', 'edit');--> statement-breakpoint
CREATE TABLE "agent_memory_writes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_memory_writes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"agent_id" integer NOT NULL,
	"entry_id" integer,
	"kind" "memory_write_kind" NOT NULL,
	"source" "memory_source",
	"ciphertext" text NOT NULL,
	"key_version" integer DEFAULT 1 NOT NULL,
	"session_id" integer,
	"run_id" integer,
	"user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_memory_entries" DROP CONSTRAINT "agent_memory_entries_last_source_run_id_runs_id_fk";
--> statement-breakpoint
ALTER TABLE "agent_memory_entries" DROP CONSTRAINT "agent_memory_entries_last_source_session_id_sessions_id_fk";
--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_entry_id_agent_memory_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."agent_memory_entries"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_memory_writes" ADD CONSTRAINT "agent_memory_writes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agent_memory_writes_entry_created_idx" ON "agent_memory_writes" USING btree ("entry_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "agent_memory_writes_agent_created_idx" ON "agent_memory_writes" USING btree ("agent_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "agent_memory_writes_reinforce_once_per_session" ON "agent_memory_writes" USING btree ("entry_id","session_id","source") WHERE "agent_memory_writes"."kind" = 'reinforce';--> statement-breakpoint
ALTER TABLE "agent_memory_entries" DROP COLUMN "last_source_run_id";--> statement-breakpoint
ALTER TABLE "agent_memory_entries" DROP COLUMN "last_source_session_id";